spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GeoffreyMakawaMbewe/NyasaLink.git
          clone-on-start: true
#          default-label: main

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/


  application:
    name: CONFIGURATION-SERVICE
server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG




#____________________________________________________________________________
#  echo "# NyasaLink" >> README.md
#  git init
#  git add README.md
#  git commit -m "first commit"
#  git branch -M main
#  git remote add origin https://github.com/GeoffreyMakawaMbewe/NyasaLink.git
#  git push -u origin main
#____________________________________________________________________________

#  git remote add origin https://github.com/GeoffreyMakawaMbewe/NyasaLink.git
#  git branch -M main
#  git push -u origin main
#____________________________________________________________________________