spring:
  application:
    name: API-GATEWAY
  cloud: # Will hold all spring cloud related configurations
    gateway:
      server:
        webmvc:
          routes:
            - id: config-service
              uri: lb://CONFIGURATION-SERVICE
              predicates:
                - Path=/config-server/**






