server:
  port: 8761 # The conventional default port for Eureka

spring:
  application:
    name: EUREKA-SERVICE # Name used internally by Eureka

eureka:
  instance:
    hostname: localhost # Hostname of the Eureka server instance
  client:
    register-with-eureka: false # Eureka server does not register with itself
    fetch-registry: false # Eureka server does not fetch registry information
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL for Eureka server
